[package]
name = "chrono-english2"
version = "0.2.0"
authors = ["Conrad Ludgate <conradludgate@gmail.com"]
edition = "2021"
description = "parses simple English dates, inspired by Linux date command"
repository = "https://github.com/conradludgate/chrono-english"
readme = "readme.md"
license="MIT"

[dependencies]
chrono = { version = "0.4.22", default-features = false, features = ["alloc", "clock"] }
logos = "0.12"
