[package]
name = "interim"
version = "0.1.0"
authors = ["Conrad Ludgate <conradludgate@gmail.com"]
edition = "2021"
description = "parses simple English dates, inspired by Linux date command, and forked from chrono-english"
repository = "https://github.com/conradludgate/interim"
readme = "README.md"
license="MIT"

[features]
default = ["std"]
std = []

[dependencies]
time = { version = "0.3", default-features = false, optional = true }
chrono = { version = "0.4.22", default-features = false, optional = true }
logos = "0.12"

[dev-dependencies]
chrono = { version = "0.4.22", default-features = false, features = ["clock"] }
time = { version = "0.3", default-features = false, features = ["formatting"] }

# Properly document all features on docs.rs
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
